version: '3.5'

services:
    draconifors_api:
        image: draconifors-api
        build:
            context: ./draconifors-api/
        container_name: draconifors_api
        volumes:
            - ./draconifors-api/src:/usr/src/app/src:delegated
            - ./draconifors-api/dist:/usr/src/app/dist:delegated
            - ./draconifors-api/circuits:/usr/src/app/circuits:delegated
            - ./draconifors-api/artifacts:/usr/src/app/artifacts:delegated    
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - draconifors_api_watch
        external_links:
            - draconifors_test
        ports:
            - 3001:3001
        command: "npm run dev"
        networks: 
            - draconifors_backend
    
    draconifors_api_watch:
        image: draconifors-api-watch
        build:
            context: ./draconifors-api
        command: "npm run build:watch"
        container_name: draconifors_api_watch
        volumes:
            - ./draconifors-api/src:/usr/src/app/src:delegated
            - ./draconifors-api/dist:/usr/src/app/dist:delegated
            - ./draconifors-api/circuits:/usr/src/app/circuits:delegated
            - ./draconifors-api/artifacts:/usr/src/app/artifacts:delegated
        networks: 
            - draconifors_backend

networks:
  draconifors_backend:
    external: true