version: "3.5"

services:
  ares_test:
    build: ./
    command: npm test
    container_name: ares_test
    restart: always
    external_links:
      - ares_api
    ports:
      - 3002:3002
    volumes:
      - ./ares-api/src:/usr/src/app/src:delegated
      - ./ares-api/dist:/usr/src/app/dist:delegated
      - ./ares-api/circuits:/usr/src/apppp/circuits:delegated
      - ./ares-api/artifacts:/usr/src/app/artifacts:delegated
    networks:
      - ares_backend  

networks:
  ares_backend:
    external: true