version: '3.5'

services:
    draconiforce_api:
        image: draconiforce-api
        build:
            context: ./draconiforce-api/
        container_name: draconiforce_api
        volumes:
            - ./draconiforce-api/src:/usr/src/app/src:delegated
            - ./draconiforce-api/dist:/usr/src/app/dist:delegated
            - ./draconiforce-api/circuits:/usr/src/app/circuits:delegated
            - ./draconiforce-api/artifacts:/usr/src/app/artifacts:delegated    
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - draconiforce_api_watch
        external_links:
            - draconiforce_test
        ports:
            - 3001:3001
        command: "npm run dev"
        networks: 
            - draconiforce_backend
    
    draconiforce_api_watch:
        image: draconiforce-api-watch
        build:
            context: ./draconiforce-api
        command: "npm run build:watch"
        container_name: draconiforce_api_watch
        volumes:
            - ./draconiforce-api/src:/usr/src/app/src:delegated
            - ./draconiforce-api/dist:/usr/src/app/dist:delegated
            - ./draconiforce-api/circuits:/usr/src/app/circuits:delegated
            - ./draconiforce-api/artifacts:/usr/src/app/artifacts:delegated
        networks: 
            - draconiforce_backend

networks:
  draconiforce_backend:
    external: true