version: "3.5"

services:
  draconifors_test:
    image: draconifors-api-test
    build: ./draconifors-api
    command: npm test
    container_name: draconifors_test
    restart: on-failure
    external_links:
      - draconifors_api
    ports:
      - 3002:3002
    volumes:
      - ./draconifors-api/src:/usr/src/app/src:delegated
      - ./draconifors-api/dist:/usr/src/app/dist:delegated
      - ./draconifors-api/circuits:/usr/src/apppp/circuits:delegated
      - ./draconifors-api/artifacts:/usr/src/app/artifacts:delegated
    networks:
      - draconifors_backend  

networks:
  draconifors_backend:
    external: true