version: '3.5'

services:
    ares_api:
        build:
            context: ./ares-api/
        container_name: ares_api
        volumes:
            - ./ares-api/src:/usr/src/app/src:delegated
            - ./ares-api/dist:/usr/src/app/dist:delegated
            - ./ares-api/circuits:/usr/src/app/circuits:delegated
            - ./ares-api/artifacts:/usr/src/app/artifacts:delegated    
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - ares_api_watch
        external_links:
            - ares_test
        ports:
            - 3001:3001
        command: "npm run dev"
        networks: 
            - ares_backend
    
    ares_api_watch:
        build:
            context: ./ares-api
            dockerfile: dockerfile
        command: "npm run build:watch"
        container_name: ares_api_watch
        volumes:
            - ./ares-api/src:/usr/src/app/src:delegated
            - ./ares-api/dist:/usr/src/app/dist:delegated
            - ./ares-api/circuits:/usr/src/app/circuits:delegated
            - ./ares-api/artifacts:/usr/src/app/artifacts:delegated
        networks: 
            - ares_backend

networks:
  ares_backend:
    external: true